name: Kernel Builder Action

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: 'Device codename (e.g. a30s)'
        required: true
      kernel_version:
        description: 'Kernel version (e.g., 1.0)'
        required: true
      build_dtb:
        description: 'Build DTB?'
        required: false
        default: 'true'
      upload_to_release:
        description: 'Upload artifact to releases (yes/no)'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:21.10

    steps:
    - name: Fix sources for EOL Ubuntu 21.10
      run: |
        sed -i 's|http://archive.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list
        sed -i 's|http://security.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list

    - name: Install packages
      run: |
        apt update
        DEBIAN_FRONTEND=noninteractive apt install -y \
          build-essential bc zip curl git \
          libncurses5-dev flex bison \
          python-is-python3 ca-certificates unzip ccache

    - name: Clone repo manually (with full history)
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git clone --recurse-submodules https://github.com/${{ github.repository }} .
        git fetch --tags
        chmod 0777 -R .
          
    - name: Check for required binaries
      shell: bash
      run: |
        REQUIRED_TOOLS=("make" "zip" "grep" "sed" "bc" "ccache" "git" "curl" "unzip")
        MISSING=0
        for tool in "${REQUIRED_TOOLS[@]}"; do
          if ! command -v "$tool" &>/dev/null; then
            echo "Missing required tool: $tool"
            MISSING=1
          fi
        done
        if [ "$MISSING" -ne 0 ]; then
          echo "Aborting due to missing tools."
          exit 1
        fi

    - name: Silence missing libmpfr.so.4 error
      run: |
        LIB_PATH=$(ldconfig -p | grep libmpfr.so.6 | head -n1 | awk '{print $NF}')
        if [ -f "$LIB_PATH" ]; then
          ln -sf "$LIB_PATH" /usr/lib/x86_64-linux-gnu/libmpfr.so.4
          echo "Symlinked libmpfr.so.4 -> $LIB_PATH"
        else
          echo "libmpfr.so.6 not found, aborting."
          exit 1
        fi

    - name: Make clean
      run: make clean -j$(nproc)

    - name: Make defconfig
      run: make ARCH=arm64 exynos7885-${{ inputs.device_name }}_oneui_defconfig -j$(nproc) ACTIONS=y

    - name: Make kernel
      run: |
        echo "Building kernel with CONFIG_LOCALVERSION=-v${{ inputs.kernel_version }}-KSU ACTIONS=y"
        make ARCH=arm64 -j$(nproc) CONFIG_LOCALVERSION="-v${{ inputs.kernel_version }}-KSU" ACTIONS=y

    - name: Build DTB
      if: ${{ inputs.build_dtb == 'true' }}
      run: |
        make ARCH=arm64 -j$(nproc) CONFIG_LOCALVERSION="-v${{ inputs.kernel_version }}-KSU" ACTIONS=y dtb.img
        cp arch/arm64/boot/dtb.img AnyKernel3/dtb.img

    - name: Zip kernel
      shell: bash
      run: |
        if [ ! -f arch/arm64/boot/Image ]; then
          echo "Build failed: Image not found"
          exit 1
        fi

        cp arch/arm64/boot/Image AnyKernel3/Image

        FILES=(
          "Image"
          "version"
          "META-INF/com/google/android/update-binary"
          "META-INF/com/google/android/updater-script"
          "tools/ak3-core.sh"
          "tools/busybox"
          "tools/magiskboot"
          "tools/tweaks.zip"
          "anykernel.sh"
        )

        [ -f "AnyKernel3/dtb.img" ] && FILES+=("dtb.img")

        cd AnyKernel3
        DEVICE="${{ inputs.device_name }}"
        DEVICE="${DEVICE^}"  # Capitalise first letter
        KERNEL_VERSION="${DEVICE} 4.4.177-v${{ inputs.kernel_version }}-KSU"
        ZIP_NAME="${KERNEL_VERSION}"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -r9 "../${ZIP_NAME}.zip" "${FILES[@]}"
        cd ..

    - name: Create git tag if missing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: "v${{ inputs.kernel_version }}"
      run: |
        if git tag | grep -q "^${TAG_NAME}$"; then
          echo "Tag '${TAG_NAME}' already exists locally."
        else
          echo "Creating and pushing tag '${TAG_NAME}'"
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG_NAME" -m "GH Actions automated release: $TAG_NAME"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin "$TAG_NAME"
        fi
        git checkout "$TAG_NAME"

    - name: Upload kernel zip to release
      if: ${{ inputs.upload_to_release == 'yes' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ inputs.kernel_version }}"
        files: "${{ env.ZIP_NAME }}.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: false

    - name: Upload kernel zip as artifact
      if: ${{ inputs.upload_to_release == 'no' }}
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-${{ inputs.kernel_version }}
        path: "${{ env.ZIP_NAME }}.zip"
